namespace MusicComposer

module NoteFactory =

    let C0 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let C1 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let C2 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let C3 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let C4 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let C5 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let C6 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let C7 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let C8 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let C9 = Note({ Name = NoteName.C; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let C0Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let C1Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let C2Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let C3Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let C4Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let C5Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let C6Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let C7Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let C8Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let C9Sharp = Note({ Name = NoteName.C; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let D0 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let D1 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let D2 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let D3 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let D4 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let D5 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let D6 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let D7 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let D8 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let D9 = Note({ Name = NoteName.D; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let D0Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let D1Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let D2Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let D3Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let D4Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let D5Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let D6Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let D7Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let D8Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let D9Sharp = Note({ Name = NoteName.D; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let D0Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C0})
    let D1Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C1})
    let D2Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C2})
    let D3Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C3})
    let D4Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C4})
    let D5Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C5})
    let D6Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C6})
    let D7Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C7})
    let D8Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C8})
    let D9Flat = Note({ Name = NoteName.D; Alter = NoteAlter.Flat; Octave = Octave.C9})

    let E0 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let E1 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let E2 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let E3 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let E4 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let E5 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let E6 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let E7 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let E8 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let E9 = Note({ Name = NoteName.E; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let E0Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let E1Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let E2Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let E3Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let E4Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let E5Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let E6Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let E7Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let E8Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let E9Sharp = Note({ Name = NoteName.E; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let E0Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C0})
    let E1Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C1})
    let E2Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C2})
    let E3Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C3})
    let E4Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C4})
    let E5Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C5})
    let E6Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C6})
    let E7Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C7})
    let E8Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C8})
    let E9Flat = Note({ Name = NoteName.E; Alter = NoteAlter.Flat; Octave = Octave.C9})

    let F0 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let F1 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let F2 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let F3 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let F4 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let F5 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let F6 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let F7 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let F8 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let F9 = Note({ Name = NoteName.F; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let F0Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let F1Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let F2Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let F3Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let F4Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let F5Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let F6Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let F7Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let F8Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let F9Sharp = Note({ Name = NoteName.F; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let G0 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let G1 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let G2 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let G3 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let G4 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let G5 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let G6 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let G7 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let G8 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let G9 = Note({ Name = NoteName.G; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let G0Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let G1Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let G2Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let G3Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let G4Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let G5Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let G6Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let G7Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let G8Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let G9Sharp = Note({ Name = NoteName.G; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let G0Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C0})
    let G1Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C1})
    let G2Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C2})
    let G3Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C3})
    let G4Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C4})
    let G5Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C5})
    let G6Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C6})
    let G7Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C7})
    let G8Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C8})
    let G9Flat = Note({ Name = NoteName.G; Alter = NoteAlter.Flat; Octave = Octave.C9})

    let A0 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let A1 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let A2 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let A3 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let A4 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let A5 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let A6 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let A7 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let A8 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let A9 = Note({ Name = NoteName.A; Alter = NoteAlter.Natural; Octave = Octave.C9})

    let A0Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C0})
    let A1Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C1})
    let A2Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C2})
    let A3Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C3})
    let A4Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C4})
    let A5Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C5})
    let A6Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C6})
    let A7Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C7})
    let A8Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C8})
    let A9Sharp = Note({ Name = NoteName.A; Alter = NoteAlter.Sharp; Octave = Octave.C9})

    let A0Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C0})
    let A1Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C1})
    let A2Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C2})
    let A3Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C3})
    let A4Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C4})
    let A5Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C5})
    let A6Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C6})
    let A7Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C7})
    let A8Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C8})
    let A9Flat = Note({ Name = NoteName.A; Alter = NoteAlter.Flat; Octave = Octave.C9})

    let B0 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C0})
    let B1 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C1})
    let B2 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C2})
    let B3 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C3})
    let B4 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C4})
    let B5 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C5})
    let B6 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C6})
    let B7 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C7})
    let B8 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C8})
    let B9 = Note({ Name = NoteName.B; Alter = NoteAlter.Natural; Octave = Octave.C9})